export const SWITCH_FOCUSE = 'header/SWITCH_FOCUSE';

export const CHANGE_MOUSE_ENTER_SEARCH_INFO_STATUS = 'CHANGE_MOUSE_ENTER_SEARCH_INFO_STATUS';

export const GET_SEARCH_INFO_DATA = 'GET_SEARCH_INFO_DATA';